import { afterEach, expect, it, vi } from 'vitest'
import { createSequencePlayback } from './useSequencePlayback'

afterEach(() => vi.useRealTimers())
it('plays messages in order, then stops', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: 1, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: 2, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: null, playing: false })
  expect(vi.getTimerCount()).toBe(0)
})
it('stops and disposes timers without late updates', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  playback.stop()
  vi.advanceTimersByTime(5000)
  expect(change).toHaveBeenLastCalledWith({ index: null, playing: false })
  playback.play(3)
  playback.dispose()
  vi.advanceTimersByTime(5000)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
})
it('replay restarts at zero and never creates duplicate timers', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  vi.advanceTimersByTime(1100)
  playback.play(3)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
  expect(vi.getTimerCount()).toBe(1)
  playback.play(0)
  expect(vi.getTimerCount()).toBe(0)
})
