import { afterEach, expect, it, vi } from 'vitest'
import { createSequencePlayback, createPlaybackEventTracker } from './useSequencePlayback'

afterEach(() => vi.useRealTimers())
it('plays messages in order, then stops', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: 1, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: 2, playing: true })
  vi.advanceTimersByTime(1100)
  expect(change).toHaveBeenLastCalledWith({ index: null, playing: false })
  expect(vi.getTimerCount()).toBe(0)
})
it('stops and disposes timers without late updates', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  playback.stop()
  vi.advanceTimersByTime(5000)
  expect(change).toHaveBeenLastCalledWith({ index: null, playing: false })
  playback.play(3)
  playback.dispose()
  vi.advanceTimersByTime(5000)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
})
it('replay restarts at zero and never creates duplicate timers', () => {
  vi.useFakeTimers()
  const change = vi.fn()
  const playback = createSequencePlayback(change)
  playback.play(3)
  vi.advanceTimersByTime(1100)
  playback.play(3)
  expect(change).toHaveBeenLastCalledWith({ index: 0, playing: true })
  expect(vi.getTimerCount()).toBe(1)
  playback.play(0)
  expect(vi.getTimerCount()).toBe(0)
})

it('reports starts/stops once per transition, without tracking every playback tick or cleanup', () => {
  vi.useFakeTimers()
  const event = vi.fn()
  const playback = createSequencePlayback(vi.fn(), event)
  playback.play(3, 'automatic')
  vi.advanceTimersByTime(3300)
  expect(event.mock.calls).toEqual([[{ action: 'play', trigger: 'automatic' }], [{ action: 'stop', reason: 'completed' }]])
  event.mockClear()
  playback.play(3)
  playback.stop()
  playback.stop()
  playback.dispose()
  expect(event.mock.calls).toEqual([[{ action: 'play', trigger: 'manual' }], [{ action: 'stop', reason: 'manual' }]])
})

it('deduplicates StrictMode autoplay and ignores automatic refreshes while retaining manual playback events', () => {
  const emit = vi.fn()
  const observe = createPlaybackEventTracker()
  const play = { action: 'play', trigger: 'automatic' } as const
  const complete = { action: 'stop', reason: 'completed' } as const
  observe(play, 'example-1', emit)
  observe(play, 'example-1', emit) // StrictMode setup replay.
  observe(complete, 'example-1', emit)
  observe(play, 'example-1', emit) // Source edit / auto-layout.
  observe(complete, 'example-1', emit)
  expect(emit.mock.calls).toEqual([[play], [complete]])
  observe({ action: 'play', trigger: 'manual' }, 'example-1', emit)
  observe({ action: 'stop', reason: 'manual' }, 'example-1', emit)
  observe(play, 'example-2', emit)
  expect(emit).toHaveBeenCalledTimes(5)
})
